openai:
  api-key: "key"
  url: "https://api.openai.com/v1/chat/completions"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/FAQ_project_24_11
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true